services:
  dev:
    build: .
    image: zenior
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev
    network_mode: bridge
    pull_policy: never

  prisma:
    image: zenior
    ports:
      - "5555:5555"
    volumes:
      - ./prisma:/app/prisma
    command: sh -c "npx prisma generate && npx prisma studio -b none"
    network_mode: bridge
    pull_policy: never
